---
blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/Infiniti151/flatpak-apps/discussions
    about: Please use discussions for general questions or community help.
