---
name: Trigger COPR Build
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - app_name: text-compare
            upstream_repo: josephmawa/TextCompare
          - app_name: concessio
            upstream_repo: ronniedroid/concessio
    steps:
      - name: Checkout Subdirectory
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sparse-checkout: |
            ${{ matrix.app_name }}
            README.md

      - name: Get Latest Upstream Tag
        id: upstream
        run: |
          TAG=$(curl -s "https://api.github.com/repos/${{ matrix.upstream_repo }}/tags" | jq -r '.[0].name')
          echo "version=${TAG#v}" >> $GITHUB_OUTPUT

      - name: Check and Trigger COPR Build
        env:
          APP: ${{ matrix.app_name }}
          NEW_VER: ${{ steps.upstream.outputs.version }}
        run: |
          SPEC="$APP/$APP.spec"
          README="README.md"

          if [ ! -f "$SPEC" ]; then
            echo -e "\e[1;31m==> Error: $SPEC not found!\e[0m"
            exit 1
          fi

          OLD_VER=$(grep -m1 '^Version:' "$SPEC" | awk '{print $2}')

          if [ "$OLD_VER" != "$NEW_VER" ]; then
            echo -e "\e[1;36m==> Bumping $APP from $OLD_VER to $NEW_VER...\e[0m"

            sed -i "s/^Version:.*/Version:        $NEW_VER/" "$SPEC"

            if [ -f "$README" ]; then
               sed -i "/| $APP |/ s/| [0-9.]* |/| $NEW_VER |/" "$README"
            fi

            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add "$SPEC" "$README"
            git commit -m "chore($APP): bump version to $NEW_VER"
            git push

            sleep 5

            BASE_URL=$(echo "${{ secrets.COPR_BASE_WEBHOOK_URL }}" | xargs)
            FINAL_URL="${BASE_URL%/}/$APP/"

            echo -e "\e[1;36m==> Triggering COPR for $APP...\e[0m"
            curl -s -X POST "$FINAL_URL"
          else
            echo -e "\e[1;32m==> $APP is already up to date ($OLD_VER).\e[0m"
          fi
